// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: gRPC/basic1/proto/todolist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddingTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AddingTodoRequest) Reset() {
	*x = AddingTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddingTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddingTodoRequest) ProtoMessage() {}

func (x *AddingTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddingTodoRequest.ProtoReflect.Descriptor instead.
func (*AddingTodoRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_basic1_proto_todolist_proto_rawDescGZIP(), []int{0}
}

func (x *AddingTodoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TogglingTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TogglingTodoRequest) Reset() {
	*x = TogglingTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TogglingTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TogglingTodoRequest) ProtoMessage() {}

func (x *TogglingTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TogglingTodoRequest.ProtoReflect.Descriptor instead.
func (*TogglingTodoRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_basic1_proto_todolist_proto_rawDescGZIP(), []int{1}
}

func (x *TogglingTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemovingTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemovingTodoRequest) Reset() {
	*x = RemovingTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovingTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovingTodoRequest) ProtoMessage() {}

func (x *RemovingTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovingTodoRequest.ProtoReflect.Descriptor instead.
func (*RemovingTodoRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_basic1_proto_todolist_proto_rawDescGZIP(), []int{2}
}

func (x *RemovingTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 响应
type TodoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *TodoResponse) Reset() {
	*x = TodoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoResponse) ProtoMessage() {}

func (x *TodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_basic1_proto_todolist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoResponse.ProtoReflect.Descriptor instead.
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_basic1_proto_todolist_proto_rawDescGZIP(), []int{3}
}

func (x *TodoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TodoResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_gRPC_basic1_proto_todolist_proto protoreflect.FileDescriptor

var file_gRPC_basic1_proto_todolist_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x31, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x64, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x25, 0x0a, 0x13, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x64,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x56, 0x0a, 0x0c, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x32, 0x9e, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x12,
	0x12, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x54, 0x6f, 0x64, 0x6f,
	0x12, 0x14, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x64, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x14, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x54, 0x6f,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x64, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_basic1_proto_todolist_proto_rawDescOnce sync.Once
	file_gRPC_basic1_proto_todolist_proto_rawDescData = file_gRPC_basic1_proto_todolist_proto_rawDesc
)

func file_gRPC_basic1_proto_todolist_proto_rawDescGZIP() []byte {
	file_gRPC_basic1_proto_todolist_proto_rawDescOnce.Do(func() {
		file_gRPC_basic1_proto_todolist_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_basic1_proto_todolist_proto_rawDescData)
	})
	return file_gRPC_basic1_proto_todolist_proto_rawDescData
}

var file_gRPC_basic1_proto_todolist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gRPC_basic1_proto_todolist_proto_goTypes = []interface{}{
	(*AddingTodoRequest)(nil),   // 0: AddingTodoRequest
	(*TogglingTodoRequest)(nil), // 1: TogglingTodoRequest
	(*RemovingTodoRequest)(nil), // 2: RemovingTodoRequest
	(*TodoResponse)(nil),        // 3: TodoResponse
}
var file_gRPC_basic1_proto_todolist_proto_depIdxs = []int32{
	0, // 0: TodoList.AddTodo:input_type -> AddingTodoRequest
	1, // 1: TodoList.ToggleTodo:input_type -> TogglingTodoRequest
	2, // 2: TodoList.RemoveTodo:input_type -> RemovingTodoRequest
	3, // 3: TodoList.AddTodo:output_type -> TodoResponse
	3, // 4: TodoList.ToggleTodo:output_type -> TodoResponse
	3, // 5: TodoList.RemoveTodo:output_type -> TodoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_basic1_proto_todolist_proto_init() }
func file_gRPC_basic1_proto_todolist_proto_init() {
	if File_gRPC_basic1_proto_todolist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPC_basic1_proto_todolist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddingTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_basic1_proto_todolist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TogglingTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_basic1_proto_todolist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovingTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_basic1_proto_todolist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_basic1_proto_todolist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_basic1_proto_todolist_proto_goTypes,
		DependencyIndexes: file_gRPC_basic1_proto_todolist_proto_depIdxs,
		MessageInfos:      file_gRPC_basic1_proto_todolist_proto_msgTypes,
	}.Build()
	File_gRPC_basic1_proto_todolist_proto = out.File
	file_gRPC_basic1_proto_todolist_proto_rawDesc = nil
	file_gRPC_basic1_proto_todolist_proto_goTypes = nil
	file_gRPC_basic1_proto_todolist_proto_depIdxs = nil
}
